backend:
  name: github
  repo: illilyelansary/KoralPTV  # ton repo GitHub
  branch: main                   # la branche de production
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}
