backend:
  name: github
  repo: illilyelansary/KoralIPTV   # ton repo GitHub
  branch: main                     # la branche principale
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "public/images/uploads"   # où seront stockées les images dans le repo
public_folder: "/images/uploads"        # chemin public des images

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"   # tu devras créer ce dossier dans ton projet
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}

  - name: "posts"
    label: "Articles"
    folder: "src/content/posts"   # tu devras créer ce dossier aussi
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Contenu", name: "body", widget: "markdown"}
